/**
 * Generate the french-common-words data file.
 *
 * Sources:
 *   - OpenSubtitles 2018 frequency list (top 50k French words by usage)
 *   - an-array-of-french-words npm package (dictionary validation)
 *
 * Methodology:
 *   1. Download frequency-ranked word list (real-world usage data)
 *   2. Intersect with dictionary to filter out proper nouns and typos
 *   3. Keep only words >= 5 chars (matching name-matching.ts minimum)
 *   4. Normalize (lowercase, remove accents)
 *   5. Output a static TypeScript Set
 *
 * Usage: npx tsx scripts/generate-french-words.ts
 */

import { writeFileSync } from "fs";
import { join } from "path";

const FREQ_URL =
  "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fr/fr_50k.txt";

const MIN_LENGTH = 5;

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[-–—]/g, " ")
    .trim();
}

async function main() {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const dictWords: string[] = require("an-array-of-french-words");
  const dictSet = new Set(dictWords);

  console.log(`Dictionary: ${dictSet.size} words`);

  // Download frequency list
  console.log("Downloading frequency list...");
  const response = await fetch(FREQ_URL);
  if (!response.ok) throw new Error(`Failed to fetch: ${response.status}`);
  const text = await response.text();
  const lines = text.trim().split("\n");
  console.log(`Frequency list: ${lines.length} entries`);

  // Parse and filter
  const seen = new Map<string, number>();

  for (const line of lines) {
    const parts = line.split(" ");
    const freq = parseInt(parts[parts.length - 1]);
    const word = parts.slice(0, -1).join(" ");

    // Must be >= MIN_LENGTH chars
    if (word.length < MIN_LENGTH) continue;

    // Must be alphabetic only (no hyphens, apostrophes, digits)
    if (!/^[a-zA-ZÀ-ÿ]+$/.test(word)) continue;

    // Must be in the dictionary (validates it's a real French word, not a proper noun)
    if (!dictSet.has(word) && !dictSet.has(word.toLowerCase())) continue;

    const normalized = normalize(word);

    // Keep highest frequency for each normalized form
    if (!seen.has(normalized) || (seen.get(normalized) ?? 0) < freq) {
      seen.set(normalized, freq);
    }
  }

  const sortedWords = [...seen.keys()].sort();

  console.log(`Filtered: ${sortedWords.length} unique normalized words`);

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/generate-french-words.ts — DO NOT EDIT MANUALLY
// Source: OpenSubtitles 2018 frequency list × an-array-of-french-words dictionary
// ${sortedWords.length.toLocaleString()} common French words (>= ${MIN_LENGTH} chars), normalized (no accents, lowercase)
// Regenerate: npx tsx scripts/generate-french-words.ts

const _words =
  ${JSON.stringify(sortedWords.join("\n"))};

export const FRENCH_COMMON_WORDS = new Set(_words.split("\\n"));
`;

  const outPath = join(__dirname, "..", "src", "data", "french-common-words.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`Written to ${outPath} (${Math.round(output.length / 1024)} KB)`);
}

main().catch(console.error);
