/**
 * LLM-as-judge for the NEEDS_REVIEW policy-title backlog.
 *
 * Titles were GENERATED by Mistral. The judge is CLAUDE (callAnthropic) — an
 * independent reviewer. For each title the judge sees the OFFICIAL amendment
 * substance and decides APPROVE / EDIT / REJECT / KEEP.
 *
 *   --sample N          stratified calibration sample, DRY-RUN, no write
 *   --all               judge the whole anchored set → report JSON, no write
 *   --load [--limit N]  dump anchored candidates + official substance to JSON,
 *                       NO LLM call — a Claude Code session judges them in-context
 *                       (no API spend) then writes the report --apply consumes.
 *   --apply --from F    apply the verdicts from report F via the approval guard
 *
 * Apply replicates the SHARED approval service (recompute → approveGuard(single,
 * override) → persistApproval), edit/reject in a transaction, NO revalidatePath
 * (public pages are ISR). Hard blockers always win, even over the judge.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { db } from "@/lib/db";
import { callAnthropic, extractToolUse } from "@/lib/api/anthropic";
import { resolveSubstanceSources } from "@/services/scrutin-policy-title/substance-resolver";
import { escapeXmlText } from "@/lib/text/escape-xml";
import {
  recomputeApprovalContext,
  persistApproval,
  isRejectedNotRevised,
  snapshot,
  asJson,
} from "@/services/scrutin-policy-title/approval";
import { approveGuard, computeCurrentWarnings } from "@/app/admin/policy-titles/approve-guard";
import type { EvidenceQuote } from "@/services/scrutin-policy-title/types";
import type { Prisma } from "@/generated/prisma";

const JUDGE_MODEL = "claude-sonnet-4-5-20250929";
const ACTOR = "llm-judge:claude-sonnet-4-5";
const REPORT_PATH = "scripts/.local/judge-report.json";
const CANDIDATES_PATH = "scripts/.local/judge-candidates.json";
const CONCURRENCY = 6;

const SYSTEM = `Tu es un relecteur éditorial rigoureux et INDÉPENDANT pour Poligraph, un observatoire citoyen de la politique française.

Un autre modèle a généré un TITRE vulgarisé pour un vote parlementaire, à partir du texte officiel d'un amendement. Ta mission : décider si ce titre peut être publié tel quel pour le grand public.

Sois CONSERVATEUR et ADVERSARIAL : cherche activement les raisons de NE PAS publier. En cas de doute, ne valide pas.

Critères :
1. ANCRAGE (le plus important) : le titre décrit-il fidèlement la mesure du <texte-officiel> ? Aucune mesure inventée ou absente, aucun contresens, aucune généralisation trompeuse.
2. CLARTÉ : titre vulgarisé, compréhensible sans connaissance parlementaire. Pas de jargon procédural ("amendement n°X", "après l'article 22" employés seuls).
3. NEUTRALITÉ : factuel, pas de jugement de valeur.

Verdicts :
- APPROVE : fidèle + clair + neutre, publiable tel quel.
- EDIT : le fond est bon mais le titre est améliorable → fournis suggestedTitle (≤140 caractères) et, si utile, suggestedSubtitle, fidèles au texte officiel.
- REJECT : titre faux, inventé, contresens, ou purement procédural irrécupérable.
- KEEP : cas ambigu qui nécessite un humain.

Réponds UNIQUEMENT via l'outil submit_verdict.`;

const TOOL = {
  name: "submit_verdict",
  description: "Rendre le verdict sur le titre généré.",
  input_schema: {
    type: "object",
    properties: {
      verdict: { type: "string", enum: ["APPROVE", "EDIT", "REJECT", "KEEP"] },
      reason: { type: "string", description: "Une phrase, en français." },
      suggestedTitle: { type: "string", description: "Requis si verdict=EDIT. ≤140 car." },
      suggestedSubtitle: { type: "string" },
    },
    required: ["verdict", "reason"],
  },
};

interface Verdict {
  verdict: "APPROVE" | "EDIT" | "REJECT" | "KEEP";
  reason: string;
  suggestedTitle?: string;
  suggestedSubtitle?: string;
}

interface Candidate {
  scrutinId: string;
  slug: string | null;
  policyTitle: string | null;
  policySubtitle: string | null;
  officialTitleSnapshot: string | null;
  confidence: string;
  coverage: number;
}

interface ReportRow extends Candidate, Verdict {}

interface LoadedCandidate extends Candidate {
  /** Official amendment substance (HTML-stripped blocks), so the in-session
   *  judge can decide grounding without any further DB access. */
  official: string;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function judgeOne(c: Candidate): Promise<Verdict | null> {
  const resolved = await resolveSubstanceSources(c.scrutinId);
  if (resolved.blocks.length === 0) return null;
  const official = resolved.blocks
    .map(
      (b) =>
        `<source field="${escapeXmlText(b.field)}" amendement="${escapeXmlText(b.meta?.amendmentNumber ?? "")}">${escapeXmlText(b.text)}</source>`
    )
    .join("\n");
  const user = `<texte-officiel>
${official}
</texte-officiel>

<titre-procedural>${escapeXmlText(c.officialTitleSnapshot ?? "")}</titre-procedural>
<titre-genere>${escapeXmlText(c.policyTitle ?? "")}</titre-genere>
<sous-titre-genere>${escapeXmlText(c.policySubtitle ?? "")}</sous-titre-genere>`;

  for (let t = 0; t < 3; t++) {
    try {
      const resp = await callAnthropic([{ role: "user", content: user }], {
        label: "judge-policy-titles",
        model: JUDGE_MODEL,
        maxTokens: 600,
        system: SYSTEM,
        tools: [TOOL],
        toolChoice: { type: "tool", name: "submit_verdict" },
      });
      return extractToolUse(resp) as Verdict | null;
    } catch (e) {
      const msg = String(e);
      if (t < 2 && (msg.includes("429") || msg.includes("529") || msg.includes("500"))) {
        await sleep(2000 * (t + 1));
        continue;
      }
      if (t < 2) {
        await sleep(800);
        continue;
      }
      throw e;
    }
  }
  return null;
}

async function loadAnchored(): Promise<Candidate[]> {
  const rows = await db.scrutinPolicyTitle.findMany({
    where: { status: "NEEDS_REVIEW", policyTitle: { not: null } },
    select: {
      scrutinId: true,
      policyTitle: true,
      policySubtitle: true,
      officialTitleSnapshot: true,
      confidence: true,
      qualitySignals: true,
      scrutin: { select: { slug: true } },
    },
  });
  return rows
    .map((r) => ({
      scrutinId: r.scrutinId,
      slug: r.scrutin?.slug ?? null,
      policyTitle: r.policyTitle,
      policySubtitle: r.policySubtitle,
      officialTitleSnapshot: r.officialTitleSnapshot,
      confidence: r.confidence,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      coverage: ((r.qualitySignals as any)?.evidenceCoverage as number) ?? 0,
    }))
    .filter((c) => c.coverage > 0);
}

async function mapPool<T, R>(
  items: T[],
  n: number,
  fn: (t: T, i: number) => Promise<R>
): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let idx = 0;
  let done = 0;
  async function worker() {
    while (idx < items.length) {
      const i = idx++;
      out[i] = await fn(items[i]!, i);
      done++;
      if (done % 25 === 0) process.stdout.write(`  …${done}/${items.length}\n`);
    }
  }
  await Promise.all(Array.from({ length: Math.min(n, items.length) }, worker));
  return out;
}

function arg(name: string): string | undefined {
  const i = process.argv.findIndex((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (i < 0) return undefined;
  const v = process.argv[i]!;
  return v.includes("=") ? v.split("=").slice(1).join("=") : process.argv[i + 1];
}
const flag = (n: string) => process.argv.some((a) => a === `--${n}`);
const log = (s = "") => console.log(s);

// ── SAMPLE (calibration) ──────────────────────────────────────────────────
async function runSample(): Promise<void> {
  const size = arg("sample") ? Number(arg("sample")) : 25;
  const anchored = await loadAnchored();
  const high = anchored.filter((c) => c.coverage >= 0.8);
  const mid = anchored.filter((c) => c.coverage >= 0.5 && c.coverage < 0.8);
  const low = anchored.filter((c) => c.coverage < 0.5);
  const nH = Math.round(size * 0.4),
    nM = Math.round(size * 0.4);
  const sample = [...high.slice(0, nH), ...mid.slice(0, nM), ...low.slice(0, size - nH - nM)];
  log(`Univers jugeable: ${anchored.length} — échantillon ${sample.length} (DRY-RUN)\n`);
  const counts: Record<string, number> = {};
  for (const c of sample) {
    const v = await judgeOne(c);
    if (!v) continue;
    counts[v.verdict] = (counts[v.verdict] ?? 0) + 1;
    log(`── ${v.verdict} [cov ${c.coverage.toFixed(2)}|${c.confidence}] ${c.slug ?? c.scrutinId}`);
    log(`   généré: ${c.policyTitle}`);
    if (v.suggestedTitle) log(`   → ${v.suggestedTitle}`);
    log(`   ${v.reason}\n`);
  }
  log("=== Récap ===\n" + JSON.stringify(counts));
}

// ── ALL (full judge → report) ─────────────────────────────────────────────
async function runAll(): Promise<void> {
  const anchored = await loadAnchored();
  log(`Jugement de ${anchored.length} titres (coverage>0), concurrence ${CONCURRENCY}, DRY-RUN…\n`);
  const verdicts = await mapPool(anchored, CONCURRENCY, async (c) => {
    const v = await judgeOne(c).catch(() => null);
    return v ? ({ ...c, ...v } as ReportRow) : null;
  });
  const rows = verdicts.filter(Boolean) as ReportRow[];
  mkdirSync("scripts/.local", { recursive: true });
  writeFileSync(
    REPORT_PATH,
    JSON.stringify({ model: JUDGE_MODEL, total: rows.length, verdicts: rows }, null, 2)
  );
  const counts: Record<string, number> = {};
  for (const r of rows) counts[r.verdict] = (counts[r.verdict] ?? 0) + 1;
  log(
    `\n=== Rapport écrit: ${REPORT_PATH} (${rows.length} jugés, ${anchored.length - rows.length} non-jugeables) ===`
  );
  log(JSON.stringify(counts));
}

// ── LOAD (dump candidates + substance, NO LLM — for in-session judging) ─────
async function runLoad(): Promise<void> {
  const anchored = await loadAnchored();
  const limit = arg("limit") ? Number(arg("limit")) : undefined;
  const subset = limit ? anchored.slice(0, limit) : anchored;
  log(
    `Résolution de la substance officielle de ${subset.length} candidats (lecture seule, aucun appel API)…`
  );
  const loaded = await mapPool(subset, CONCURRENCY, async (c) => {
    try {
      const resolved = await resolveSubstanceSources(c.scrutinId);
      if (resolved.blocks.length === 0) return null;
      const official = resolved.blocks
        .map(
          (b) =>
            `[${b.field}${b.meta?.amendmentNumber ? ` · amdt ${b.meta.amendmentNumber}` : ""}]\n${b.text}`
        )
        .join("\n\n");
      return { ...c, official } as LoadedCandidate;
    } catch {
      return null;
    }
  });
  const rows = loaded.filter(Boolean) as LoadedCandidate[];
  mkdirSync("scripts/.local", { recursive: true });
  writeFileSync(CANDIDATES_PATH, JSON.stringify({ total: rows.length, candidates: rows }, null, 2));
  log(
    `\n=== ${rows.length} candidats écrits dans ${CANDIDATES_PATH} (${subset.length - rows.length} sans substance résolvable, ignorés) ===`
  );
  log(
    `Étapes suivantes: juger chaque titre en session → écrire ${REPORT_PATH} → --apply --from ${REPORT_PATH}.`
  );
}

// ── APPLY (from report) ────────────────────────────────────────────────────
async function applyApprove(scrutinId: string, reason: string): Promise<string> {
  const ctx = await recomputeApprovalContext(scrutinId);
  if (await isRejectedNotRevised(ctx.row)) return "skip:REJECTED_NOT_REVISED";
  const res = approveGuard({
    row: ctx.row,
    currentInputHash: ctx.currentInputHash,
    currentWarnings: ctx.currentWarnings,
    evidenceDrift: ctx.evidenceDrift,
    mode: "single",
    override: { reason, actor: ACTOR },
  });
  if (!res.ok) return "skip:" + (res.hardBlockers.join("+") || "GUARD");
  await persistApproval(ctx, { actor: ACTOR, approvalOverride: { reason, actor: ACTOR } });
  return "approved";
}

async function applyEdit(r: ReportRow): Promise<string> {
  const title = (r.suggestedTitle ?? "").trim();
  if (!title || title.length > 140) return "skip:BAD_SUGGESTION";
  const subtitle = (r.suggestedSubtitle ?? "").trim() || null;
  const ctx = await recomputeApprovalContext(r.scrutinId);
  const { row, blocks } = ctx;
  const evidenceQuotes = (row.evidenceQuotes ?? []) as unknown as EvidenceQuote[];
  const newWarnings = computeCurrentWarnings(title, subtitle, evidenceQuotes, blocks);
  await db.$transaction(async (tx) => {
    await tx.scrutinPolicyTitleRevision.create({
      data: {
        policyTitleId: row.id,
        snapshot: {
          ...(snapshot(row) as object),
          previousPolicyTitle: row.policyTitle,
          previousPolicySubtitle: row.policySubtitle,
        } as Prisma.InputJsonValue,
        action: "edited",
        actorId: ACTOR,
      },
    });
    await tx.scrutinPolicyTitle.update({
      where: { id: row.id },
      data: {
        policyTitle: title,
        policySubtitle: subtitle,
        editedFromGenerated: true,
        currentWarnings: asJson(newWarnings),
      },
    });
  });
  // Approve the edited title (re-recomputes with the new title).
  const r2 = await applyApprove(r.scrutinId, `EDIT — ${r.reason}`);
  return r2 === "approved" ? "edited+approved" : "edited+" + r2;
}

async function applyReject(scrutinId: string, reason: string): Promise<string> {
  const row = await db.scrutinPolicyTitle.findUnique({ where: { scrutinId } });
  if (!row) return "skip:NO_ROW";
  await db.$transaction(async (tx) => {
    await tx.scrutinPolicyTitleRevision.create({
      data: {
        policyTitleId: row.id,
        snapshot: { ...(snapshot(row) as object), reason } as Prisma.InputJsonValue,
        action: "rejected",
        actorId: ACTOR,
      },
    });
    await tx.scrutinPolicyTitle.update({ where: { id: row.id }, data: { status: "REJECTED" } });
  });
  return "rejected";
}

async function runApply(): Promise<void> {
  const from = arg("from") ?? REPORT_PATH;
  const report = JSON.parse(readFileSync(from, "utf8")) as { verdicts: ReportRow[] };
  const rows = report.verdicts;
  log(`Application de ${rows.length} verdicts depuis ${from}…\n`);
  const outcomes: Record<string, number> = {};
  let i = 0;
  for (const r of rows) {
    let outcome: string;
    try {
      const reason = `LLM judge (Claude): ${r.reason}`.slice(0, 280);
      if (r.verdict === "APPROVE") outcome = await applyApprove(r.scrutinId, reason);
      else if (r.verdict === "EDIT") outcome = await applyEdit(r);
      else if (r.verdict === "REJECT") outcome = await applyReject(r.scrutinId, reason);
      else outcome = "kept";
    } catch (e) {
      outcome = "error:" + String(e).slice(0, 60);
    }
    outcomes[outcome] = (outcomes[outcome] ?? 0) + 1;
    if (++i % 50 === 0) process.stdout.write(`  …${i}/${rows.length}\n`);
  }
  log("\n=== Résultats application ===");
  log(JSON.stringify(outcomes, null, 2));
}

async function main(): Promise<void> {
  if (flag("apply")) await runApply();
  else if (flag("load")) await runLoad();
  else if (flag("all")) await runAll();
  else await runSample();
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
