-- Enable RLS on all existing tables (no policies = block all access via anon/authenticated keys)
-- Prisma connects as postgres role which bypasses RLS, so this is safe
-- Applied 2026-02-12

ALTER TABLE "AdminUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Affair" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AffairEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Amendment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Candidacy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatConversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatEmbedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Declaration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Election" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ElectionRound" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EuropeanGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalId" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FactCheck" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FactCheckMention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LegislativeDossier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Mandate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Party" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PartyMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Politician" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PressArticle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PressArticleMention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PressArticlePartyMention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Scrutin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Source" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncMetadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vote" ENABLE ROW LEVEL SECURITY;

-- Auto-enable RLS on future tables
CREATE OR REPLACE FUNCTION auto_enable_rls()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
DECLARE
  obj record;
BEGIN
  FOR obj IN SELECT * FROM pg_event_trigger_ddl_commands() WHERE command_tag = 'CREATE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', obj.object_identity);
  END LOOP;
END;
$$;

DROP EVENT TRIGGER IF EXISTS enable_rls_on_create;
CREATE EVENT TRIGGER enable_rls_on_create
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE')
  EXECUTE FUNCTION auto_enable_rls();
